# Change these first
owner: peerconcept # Your GitHub organization or username, where this repository lives
repo: uptime-monitor # The name of this repository

sites:
  - name: Auction Forecast
    url: https://auctionforecast.com
  - name: PeerConcept
    url: https://peerconcept.com
  - name: MKT staging
    url: https://staging.mykidstales.com
  - name: MKT prod
    url: https://mykidstales.com
  - name: MKT API staging
    url: https://staging.mykidstales.com/api/site/health
  - name: MKT API prod
    url: https://mykidstales.com/api/site/health
    #- name: IPv6 test
    #url: forwardemail.net
    #port: 80
    #check: "tcp-ping"
    #ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
