# Change these first
owner: peerconcept # Your GitHub organization or username, where this repository lives
repo: uptime-monitor # The name of this repository

sites:
  - name: Auction Forecast
    url: https://auctionforecast.com
    __dangerous__insecure: true
    assignees:
      - bob-the-coder
  - name: PeerConcept
    url: https://peerconcept.com
  - name: MKT staging
    url: https://staging.mykidstales.com
  - name: MKT prod
    url: https://mykidstales.com
    assignees:
      - bob-the-coder
  - name: MKT API staging
    url: $URL_MKT_API_STAGING
  - name: MKT API prod
    url: $URL_MKT_API_PRODUCTION
    assignees:
      - bob-the-coder
  - name: Deep Future Analytics (production)
    url: https://mgr.dfacecl.com/
    expectedStatusCodes:
      - 405
      - 200
    maxResponseTime: 5000
  - name: Deep Future Analytics API (production)
    url: https://mgr.dfacecl.com/api/v1/user/sign-in/
    method: POST
    body: '{"email": "hello@monitoring", "password": "secret"}' 
    expectedStatusCodes:
      - 403

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.peerconcept.com
  #baseUrl: /uptime-monitor
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  logoUrl: https://media-exp1.licdn.com/dms/image/C4D0BAQFEIVCCESYEiQ/company-logo_200_200/0/1653762809136?e=2147483647&v=beta&t=8VgPDLOswn7l453v9wPC3tCLeXdAibGld6GwXDL9OD0
  name: Uptime Monitor
  theme: dark
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introTitle: ""
  introMessage: This is the status page for all the websites and online services monitored by PeerConcept.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
